#pragma once

#include <QCheckBox>
#include <QLayout>
#include <QLineEdit>
#include <QPushButton>
#include <QSharedPointer>
#include <QTextEdit>
#include <QVector>
#include <QWidget>
#include <qboxlayout.h>
#include <qhashfunctions.h>
#include <qtmetamacros.h>

#include "gcode/gcode_meta.h"
#include "geometry/segment_base.h"

namespace ORNL {
/*!
 * \class GcodeExport
 * \brief Window that allows users to export gcode and project information
 */
class GcodeExport : public QWidget {
    Q_OBJECT
  public:
    //! \brief Constructor
    explicit GcodeExport(QWidget* parent);

    //! \brief Sets default name for file based on part control widget
    //! \param name: name of top-most part in control widget when window is opened
    void setDefaultName(QString name);

    //! \brief Destructor
    ~GcodeExport();

  public slots:
    //! \brief Handler to receive necessary information once the slice is complete and
    //! gcode generated.  Necessary to add final header comments if user opts to supply any
    //! \param tempLocation current location of temporary gcode file
    //! \param meta Most recent meta used
    void updateOutputInformation(QString tempLocation, GcodeMeta meta);

    //! \brief Receives parsed G-code segments used for optional companion model output.
    //! \param gcode Segments generated by GCodeLoader.
    void updateVisualizationInformation(QVector<QVector<QSharedPointer<SegmentBase>>> gcode);

    //! \brief Clears parsed G-code visualization segments while a new file is loading.
    void clearVisualizationInformation();

  protected:
    //! \brief Close event override to reset form values
    void closeEvent(QCloseEvent* event);

  private slots:
    //! \brief Handler for export button click
    void exportGcode();

    //! \brief Handler to show completion message at the end of export
    //! \param path Path file was saved to
    //! \param filename Name of the file saved
    void showComplete(QString path, QString filename);

  private:
    //! \brief Updates as-printed STL option availability based on visualization state.
    void updateAsPrintedModelOptionState();

    //! \brief Layout for widget
    QVBoxLayout* m_layout;

    //! \brief UI components in widget
    QLineEdit* m_operator_input;
    QTextEdit* m_description_input;
    QCheckBox* m_gcode_file_checkbox;
    QCheckBox* m_auxiliary_file_checkbox;
    QCheckBox* m_as_printed_model_checkbox;
    QCheckBox* m_as_printed_centerline_checkbox;
    QCheckBox* m_project_file_checkbox;
    QCheckBox* m_bundle_files_checkbox;

    //! \brief Most recently used meta
    GcodeMeta m_most_recent_meta;

    //! \brief The location of the current temporary file that holds the sliced gcode
    QString m_location;

    //! \brief Most recently parsed G-code visualization segments.
    QVector<QVector<QSharedPointer<SegmentBase>>> m_gcode;

    //! \brief Whether m_gcode belongs to the most recent completed G-code load.
    bool m_has_gcode_visualization;

    //! \brief Default file name
    QString m_default_name;

}; // class GcodeExport
} // namespace ORNL
