#include "threading/gcode_amcm_saver.h"

#include "QDir"
#include "QFile"
#include "QRegularExpression"
#include "QStringBuilder"
#include "QStringList"
#include "QTextStream"
#include "managers/settings/settings_manager.h"
#include <qmath.h>

namespace ORNL {
GCodeAMCMSaver::GCodeAMCMSaver(QString tempLocation, QString path, QString filename, QString text, GcodeMeta meta)
    : m_temp_location(tempLocation), m_path(path), m_filename(filename), m_text(text), m_selected_meta(meta) {
    // NOP
}

void GCodeAMCMSaver::run() {
    // First, get necessary parameters from settings to rotate all pathing
    QChar comma(','), newline('\n'), space(' '), x('X'), y('Y'), z('Z'), f('F'), s('S'), zero('0');
    qint16 layerNum = 0;
    QStringList lines = m_text.split(newline);
    QString G0("G0"), G1("G1"), M3("M3 "), M5("M5"), commaSpace(", ");
    QString xval("0"), yval("0"), zval("0"), velocity, feedrate;
    QString aval = QString::number(qRadiansToDegrees(GSM->getGlobal()->setting<Angle>(PRS::MachineSetup::kAxisA)()));
    QString bval = QString::number(qRadiansToDegrees(GSM->getGlobal()->setting<Angle>(PRS::MachineSetup::kAxisB)()));
    QString cval = QString::number(qRadiansToDegrees(GSM->getGlobal()->setting<Angle>(PRS::MachineSetup::kAxisC)()));
    QString maxVelocity = QString::number(
        GSM->getGlobal()->setting<Velocity>(PRS::MachineSpeed::kMaxXYSpeed).to(m_selected_meta.m_velocity_unit), 'f',
        4);
    zval = QString::number(
        GSM->getGlobal()->setting<Distance>(PRS::Dimensions::kZMax).to(m_selected_meta.m_distance_unit), 'f', 4);
    feedrate = QString::number(0);

    QFile tempFile(m_temp_location % "temp");
    if (tempFile.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        QTextStream out(&tempFile);
        out << m_text;
        tempFile.close();

        QFile::rename(tempFile.fileName(), m_filename);
    }

    QFileInfo fi(m_filename);
    QString filePath = fi.absolutePath() + QDir::separator() + fi.baseName() + "_output.src";

    QFile file(filePath);
    file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text);
    QTextStream out(&file);

    // File Header
    out << "&ACCESS RVP" % newline;
    out << "&REL 1" % newline;
    out << "&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe" % newline;
    out << "&PARAM EDITMASK = *" % newline;
    out << "DEF Hexagon ( )" % newline % newline;

    out << "; GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )" % newline;
    out << "; INTERRUPT ON 3" % newline % newline;

	out << ";FOLD Initialise and set default speed" % newline;
	out << "BAS (#INITMOV,0)" % newline;
	out << "BAS (#VEL_PTP,100)" % newline;
	out << "BAS (#ACC_PTP,20)" % newline;
	out << "$VEL.CP=0.2" % newline;
	out << "BAS (#TOOL,0)" % newline;
	out << "BAS (#BASE,0)" % newline;
	out << ";ENDFOLD" % newline % newline;

	out << ";;FOLD STARTPOS" % newline;
	out << ";$BWDSTART = FALSE" % newline;
	out << ";PDAT_ACT = PDEFAULT" % newline;
	out << ";BAS(#PTP_DAT)" % newline;
	out << ";FDAT_ACT = {TOOL_NO 0,BASE_NO 0,IPO_FRAME #BASE}" % newline;
	out << ";BAS(#FRAMES)" % newline;
	out << ";;ENDFOLD" % newline % newline;

	out << "$ADVANCE = 5" % newline;

	out << ";FOLD ---- Quickly skip BCO ----" % newline;
	out << "; PTP $AXIS_ACT" % newline;
	out << ";ENDFOLD" % newline % newline;

	out << ";FOLD ---- GO HOME ----" % newline;
	out << "; PTP {A1 0.000, A2 -90.000, A3 90.000, A4 0.000, A5 0.000, A6 0.000, E1 0, E2 0, E3 0, E4 0, E5 0, E6 0}" % newline;
	out << ";ENDFOLD" % newline % newline;

	out << "; Program generated by ORNL Slicer for KUKA KR 300 R2500 ultra" % newline;
	out << "; Using nominal kinematics." % newline;
	out << "$APO.CPTP = 1.000" % newline;
	out << "$APO.CDIS = 1.000" % newline;
	out << "$VEL.CP = 0.06000" % newline;
	out << "; ---- Setting reference (Base) ----" % newline;
	out << "; BASE_DATA[14] = {FRAME: X 1022.920,Y -1522.720,Z -588.000,A 135.000,B 0.000,C 0.000}" % newline;
	out << "; $BASE = {FRAME: X 1022.920,Y -1522.720,Z -588.000,A 135.000,B 0.000,C 0.000}" % newline;
	out << "$BASE = BASE_DATA[14]" % newline;
	out << "; --------------------------" % newline;
	out << "; ---- Setting tool (TCP) ----" % newline;
	out << "; TOOL_DATA[5] = {FRAME: X 843.812,Y 0.000,Z 301.216,A 0.000,B 0.000,C -90.000}" % newline;
	out << "; $TOOL = {FRAME: X 843.812,Y 0.000,Z 301.216,A 0.000,B 0.000,C -90.000}" % newline;
	out << "$TOOL = TOOL_DATA[5]" % newline;
	out << "; --------------------------" % newline;
	out << "; Show Tool 5" % newline;
	out << "PTP {A1 60.68200,A2 -65.00000,A3 124.01700,A4 18.60870,A5 -57.89280,A6 -10.14630,E1 0.00000} C_PTP" % newline;


    QString line;

    for (int i = 0; i < lines.size(); i++)
    {
        line = lines[i];
        if (line.startsWith(G0)) {
            velocity = QString::number(
                GSM->getGlobal()->setting<Velocity>(PS::Travel::kSpeed).to(m_selected_meta.m_velocity_unit), 'f',
                4);
            QString temp = line.mid(0, line.indexOf(m_selected_meta.m_comment_starting_delimiter));
            QVector<QString> params = temp.split(space);

            if (params[0] == G0) {
                for (int i = 1, end = params.size(); i < end; ++i) {
                    if (params[i].startsWith(x))
                        xval = params[i].mid(1);
                    else if (params[i].startsWith(y))
                        yval = params[i].mid(1);
                    else if (params[i].startsWith(z))
                        zval = params[i].mid(1);
                }
            }

            if (velocity != feedrate) {
                out << "$VEL.CP = " % velocity % newline;
                feedrate = velocity;
            }

            out << "LIN {X " % xval % ", Y " % yval % ", Z " % zval % ", A " % aval % ", B " % bval % ", C " %
                           cval % ", E1 0.000} C_DIS" % newline;
        }
        else if (line.startsWith(G1)) {
            QString temp = line.mid(0, line.indexOf(m_selected_meta.m_comment_starting_delimiter));
            QVector<QString> params = temp.split(space);

            if (params[0] == G1) {
                for (int i = 1, end = params.size(); i < end; ++i) {
                    if (params[i].startsWith(x))
                        xval = params[i].mid(1);
                    else if (params[i].startsWith(y))
                        yval = params[i].mid(1);
                    else if (params[i].startsWith(z))
                        zval = params[i].mid(1);
                    else if (params[i].startsWith(f))
                        velocity = params[i].mid(1);
                }
            }
            if (velocity != feedrate) {
                out << "$VEL.CP = " % velocity % newline;
                feedrate = velocity;
            }

            out << "LIN {X " % xval % ", Y " % yval % ", Z " % zval % ", A " % aval % ", B " % bval % ", C " %
                           cval % ", E1 0.000} C_DIS" % newline;
            if (line.contains("S0")){
                out << "; Stop Extrusion" % newline;
            }
        }
        else if (line.startsWith(M3)) {
            out << "; Start Extrusion" % newline;
        }
        else if (line.startsWith(M5)) {
            out << "; Stop Extrusion" % newline;
        }
    }

    out << newline % "END";
    file.close();
}

} // namespace ORNL
