#include "threading/gcode_amcm_saver.h"

#include <QDir>
#include <QFile>
#include <QRegularExpression>
#include <QStringBuilder>
#include <QStringList>
#include <QTextStream>
#include <qcontainerfwd.h>
#include <qfileinfo.h>
#include <qmath.h>
#include <qobject.h>
#include <qtypes.h>

#include "gcode/gcode_meta.h"
#include "managers/settings/settings_manager.h"
#include "units/unit.h"
#include "utilities/constants.h"

namespace ORNL {
GCodeAMCMSaver::GCodeAMCMSaver(QString tempLocation, QString path, QString filename, QString text, GcodeMeta meta)
    : m_temp_location(tempLocation), m_path(path), m_filename(filename), m_text(text), m_selected_meta(meta) {
    // NOP
}

void GCodeAMCMSaver::run() {
    // First, get necessary parameters from settings to rotate all pathing
    QChar comma(','), newline('\n'), space(' '), x('X'), y('Y'), z('Z'), f('F'), s('S'), zero('0');
    qint16 layerNum = 0;
    bool extruderOn = false, sync = true;
    QStringList lines = m_text.split(newline);
    QString G0("G0"), G1("G1"), M3("M3 "), M5("M5"), commaSpace(", ");
    QString xval("0"), yval("0"), zval("0"), velocity, feedrate;
    QString aval = QString::number(qRadiansToDegrees(GSM->getGlobal()->setting<Angle>(PRS::MachineSetup::kAxisA)()));
    QString bval = QString::number(qRadiansToDegrees(GSM->getGlobal()->setting<Angle>(PRS::MachineSetup::kAxisB)()));
    QString cval = QString::number(qRadiansToDegrees(GSM->getGlobal()->setting<Angle>(PRS::MachineSetup::kAxisC)()));
    QString maxVelocity = QString::number(
        GSM->getGlobal()->setting<Velocity>(PRS::MachineSpeed::kMaxXYSpeed).to(m_selected_meta.m_velocity_unit), 'f',
        4);
    zval = QString::number(
        GSM->getGlobal()->setting<Distance>(PRS::Dimensions::kZMax).to(m_selected_meta.m_distance_unit), 'f', 4);
    feedrate = QString::number(0);

    QFile tempFile(m_temp_location % "temp");
    if (tempFile.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        QTextStream out(&tempFile);
        out << m_text;
        tempFile.close();

        QFile::rename(tempFile.fileName(), m_filename);
    }

    QFileInfo fi(m_filename);
    QString filePath = fi.absolutePath() + QDir::separator() + fi.baseName() + "_output.src";

    QFile file(filePath);
    file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text);
    QTextStream out(&file);

    // File Header
    out << "&ACCESS RVP" % newline;
    out << "&REL 2" % newline;
    out << "&PARAM EDITMASK = *" % newline;
    out << "&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe" % newline;
    out << "DEF Hexagon ( )" % newline % newline;

    out << "; GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )" % newline;
    out << "; INTERRUPT ON 3" % newline % newline;

    out << ";FOLD Initialise and set default speed" % newline;
    out << "BAS (#INITMOV,0)" % newline;
    out << "BAS (#VEL_PTP,25)" % newline;
    out << "BAS (#ACC_PTP,20)" % newline;
    out << "$VEL.CP=0.2" % newline;
    out << "BAS (#TOOL,0)" % newline;
    out << "BAS (#BASE,0)" % newline;
    out << ";ENDFOLD" % newline % newline;

    out << ";;FOLD STARTPOS" % newline;
    out << ";$BWDSTART = FALSE" % newline;
    out << ";PDAT_ACT = PDEFAULT" % newline;
    out << ";BAS(#PTP_DAT)" % newline;
    out << ";FDAT_ACT = {TOOL_NO 0,BASE_NO 0,IPO_FRAME #BASE}" % newline;
    out << ";BAS(#FRAMES)" % newline;
    out << ";;ENDFOLD" % newline % newline;

    out << "$ADVANCE = 5" % newline;

    out << "; Program generated by ORNLSlicer for KUKA KR 300 R2500 ultra" % newline;
    out << "; Using nominal kinematics." % newline;
    out << "$APO.CPTP = 1.000" % newline;
    out << "$APO.CDIS = 1.000" % newline;
    out << "$VEL.CP = 0.06000" % newline;
    out << "; ---- Setting reference (Base) ----" % newline;
    // out << "; BASE_DATA[14] = {FRAME: X 1022.920,Y -1522.720,Z -588.000,A 135.000,B 0.000,C 0.000}" % newline;
    // out << "; $BASE = {FRAME: X 1022.920,Y -1522.720,Z -588.000,A 135.000,B 0.000,C 0.000}" % newline;
    out << "$BASE = BASE_DATA[" % QString::number(GSM->getGlobal()->setting<int>(PRS::MachineSetup::kBaseCoordinate)) %
               "]" % newline;
    out << "; --------------------------" % newline;
    out << "; ---- Setting tool (TCP) ----" % newline;
    // out << "; TOOL_DATA[5] = {FRAME: X 843.812,Y 0.000,Z 301.216,A 0.000,B 0.000,C -90.000}" % newline;
    // out << "; $TOOL = {FRAME: X 843.812,Y 0.000,Z 301.216,A 0.000,B 0.000,C -90.000}" % newline;
    out << "$TOOL = TOOL_DATA[" % QString::number(GSM->getGlobal()->setting<int>(PRS::MachineSetup::kToolCoordinate)) %
               "]" % newline;
    out << "; --------------------------" % newline;
    out << "; Show Tool " % QString::number(GSM->getGlobal()->setting<int>(PRS::MachineSetup::kToolCoordinate)) %
               newline;
    out << "PTP {A1 2.22261,A2 -70.64010,A3 83.97050,A4 103.99200,A5 44.42060,A6 -109.23300,E1 0.00000} C_PTP" %
               newline;
    if (GSM->getGlobal()->setting<int>(ES::FileOutput::kAMCMDataLogging)) {
        out << "Logging_Enabled=TRUE" % newline;
    }

    QString line;

    for (int i = 0; i < lines.size(); i++) {
        line = lines[i];
        if (line.startsWith(G0)) {
            velocity = QString::number(
                GSM->getGlobal()->setting<Velocity>(PS::Travel::kSpeed).to(m_selected_meta.m_velocity_unit) / 1000.0 /
                    60.0,
                'f', 4); // Meta uses mm/min, but AMCM needs m/s
            QString temp = line.mid(0, line.indexOf(m_selected_meta.m_comment_starting_delimiter));
            QVector<QString> params = temp.split(space);

            if (params[0] == G0) {
                for (int i = 1, end = params.size(); i < end; ++i) {
                    if (params[i].startsWith(x))
                        xval = params[i].mid(1);
                    else if (params[i].startsWith(y))
                        yval = params[i].mid(1);
                    else if (params[i].startsWith(z))
                        zval = params[i].mid(1);
                }
            }

            if (velocity != feedrate) {
                out << "$VEL.CP = " % velocity % newline;
                feedrate = velocity;
            }

            out << "LIN {X " % xval % ", Y " % yval % ", Z " % zval % ", A " % aval % ", B " % bval % ", C " % cval %
                       ", E1 0.000} C_DIS" % newline;
        }
        else if (line.startsWith(G1)) {
            QString temp = line.mid(0, line.indexOf(m_selected_meta.m_comment_starting_delimiter));
            QVector<QString> params = temp.split(space);

            if (params[0] == G1) {
                for (int i = 1, end = params.size(); i < end; ++i) {
                    if (params[i].startsWith(x))
                        xval = params[i].mid(1);
                    else if (params[i].startsWith(y))
                        yval = params[i].mid(1);
                    else if (params[i].startsWith(z))
                        zval = params[i].mid(1);
                    else if (params[i].startsWith(f))
                        velocity = QString::number(params[i].mid(1).toDouble() / 1000.0 / 60.0, 'f', 4);
                }
            }
            if (velocity != feedrate) {
                out << "$VEL.CP = " % velocity % newline;
                feedrate = velocity;
            }

            if (line.contains("S0") && extruderOn) {
                out << "; Stop Extrusion" % newline;
                out << "$OUT[25]=True" % newline;
                out << "WAIT SEC 0.2" % newline;
                out << "$OUT[25]=False" % newline;
                extruderOn = false;
            }

            out << "LIN {X " % xval % ", Y " % yval % ", Z " % zval % ", A " % aval % ", B " % bval % ", C " % cval %
                       ", E1 0.000} C_DIS" % newline;
        }
        else if (line.startsWith(M3)) {
            out << "; Start Extrusion" % newline;
            out << "$VEL.CP = " % velocity % newline;
            out << "IF ($MODE_OP==#AUT) THEN" % newline;
            out << "	$OUT[24]=True" % newline;
            out << "	WAIT SEC 0.5" % newline;
            out << "	$OUT[24]=False" % newline;
            out << "ELSE" % newline;
            out << "	$OUT[25]=True" % newline;
            out << "	WAIT SEC 0.5" % newline;
            out << "	$OUT[25]=False" % newline;
            extruderOn = true;
            out << "ENDIF" % newline;
            if (sync) {
                out << "CHAMP_EXTR_SYNC=TRUE" % newline;
                sync = false;
            }
        }
        else if (line.startsWith(M5) && extruderOn) {
            out << "; Stop Extrusion" % newline;
            out << "$OUT[25]=True" % newline;
            out << "WAIT SEC 0.2" % newline;
            out << "$OUT[25]=False" % newline;
            extruderOn = false;
        }
    }

    out << "CHAMP_EXTR_SYNC=FALSE" % newline;
    if (GSM->getGlobal()->setting<int>(ES::FileOutput::kAMCMDataLogging)) {
        out << "Logging_Enabled=FALSE" % newline;
    }
    out << newline % "END";
    file.close();
}

} // namespace ORNL
