include_guard(DIRECTORY)

include(git)
include(version)

function(FetchBuildInfo)
    FetchVersion()
    set(BUILD_INFO_VERSION "${RESULT_VAR}")

    FetchRevHash()
    set(BUILD_INFO_GIT_REVISION "${RESULT_VAR}")

    if(CMAKE_CONFIGURATION_TYPES)
        set(BUILD_INFO_CONFIGURATION "multi-config")
    elseif(CMAKE_BUILD_TYPE)
        set(BUILD_INFO_CONFIGURATION "${CMAKE_BUILD_TYPE}")
    else()
        set(BUILD_INFO_CONFIGURATION "unspecified")
    endif()

    set(RESULT_VAR "${BUILD_INFO_VERSION}" PARENT_SCOPE)
    set(ORNLSLICER_BUILD_GIT_REVISION "${BUILD_INFO_GIT_REVISION}" PARENT_SCOPE)
    set(ORNLSLICER_BUILD_CONFIGURATION "${BUILD_INFO_CONFIGURATION}" PARENT_SCOPE)
    set(ORNLSLICER_PACKAGE_TYPE "${ORNLSLICER_PACKAGE_TYPE}" PARENT_SCOPE)
endfunction()
